#META TABLE CONNECT CONFIG
META_SQL_DBNAME = 'flasktemp'
META_SQL_DBHOST = 'localhost'
META_SQL_DBUSER = 'root'
META_SQL_DBPASSWORD = 'yoyo'

#INDEX TABLE CONNECT CONFIG
INDEX_SQL_DBNAME = '10.237.27.67'
INDEX_SQL_DBHOST = 'power_nexus'
INDEX_SQL_DBUSER = 'root'
INDEX_SQL_DBPASSWORD = 'yoyo'

##META TABLE NAMES
META_TABLE_USER = 'users'
META_TABLE_UUID = 'uuidtable'

##INDEX TABLE NAMES
INDEX_TABLE_ENTITIES = 'entities'







