#META TABLE CONNECT CONFIG
META_SQL_DBNAME = 'flasktemp'
META_SQL_DBHOST = 'localhost'
META_SQL_DBUSER = 'root'
META_SQL_DBPASSWORD = 'yoyo'
META_SQL_DBPORT = 3306

#INDEX TABLE CONNECT CONFIG
INDEX_SQL_DBNAME = 'power_nexus'
INDEX_SQL_DBHOST = '10.237.27.67'
INDEX_SQL_DBUSER = 'nexus'
INDEX_SQL_DBPASSWORD = 'yoyo'
INDEX_SQL_DBPORT = 3306

#SOLR CONFIG
SOLR_HOST = '10.237.27.67'
SOLR_PORT = 8983
SOLR_CORE = 'mtp2'

##META TABLE NAMES
META_TABLE_USER = 'users'
META_TABLE_UUID = 'uuidtable'

##INDEX TABLE NAMES
INDEX_TABLE_ENTITIES = 'entities'







